#############################################################################
# Makefile for building: graphy
# Generated by qmake (2.01a) (Qt 4.8.3) on: Fri Apr 11 20:36:23 2014
# Project:  graphy.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile graphy.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lbluetooth -lcwiid -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwidget.cpp \
		imagewidget.cpp \
		capture.cpp \
		formatconvert.cpp \
		cameraprocess.cpp \
		bluetoothprocess.cpp \
		textedit.cpp \
		mycanvas.cpp moc_mainwidget.cpp \
		moc_imagewidget.cpp \
		moc_cameraprocess.cpp \
		moc_bluetoothprocess.cpp \
		moc_textedit.cpp \
		moc_mycanvas.cpp
OBJECTS       = main.o \
		mainwidget.o \
		imagewidget.o \
		capture.o \
		formatconvert.o \
		cameraprocess.o \
		bluetoothprocess.o \
		textedit.o \
		mycanvas.o \
		moc_mainwidget.o \
		moc_imagewidget.o \
		moc_cameraprocess.o \
		moc_bluetoothprocess.o \
		moc_textedit.o \
		moc_mycanvas.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		graphy.pro
QMAKE_TARGET  = graphy
DESTDIR       = 
TARGET        = graphy

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: graphy.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile graphy.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile graphy.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/graphy1.0.0 || $(MKDIR) .tmp/graphy1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/graphy1.0.0/ && $(COPY_FILE) --parents mainwidget.h imagewidget.h capture.h formatconvert.h cameraprocess.h bluetoothprocess.h textedit.h mycanvas.h .tmp/graphy1.0.0/ && $(COPY_FILE) --parents main.cpp mainwidget.cpp imagewidget.cpp capture.cpp formatconvert.cpp cameraprocess.cpp bluetoothprocess.cpp textedit.cpp mycanvas.cpp .tmp/graphy1.0.0/ && (cd `dirname .tmp/graphy1.0.0` && $(TAR) graphy1.0.0.tar graphy1.0.0 && $(COMPRESS) graphy1.0.0.tar) && $(MOVE) `dirname .tmp/graphy1.0.0`/graphy1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/graphy1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwidget.cpp moc_imagewidget.cpp moc_cameraprocess.cpp moc_bluetoothprocess.cpp moc_textedit.cpp moc_mycanvas.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwidget.cpp moc_imagewidget.cpp moc_cameraprocess.cpp moc_bluetoothprocess.cpp moc_textedit.cpp moc_mycanvas.cpp
moc_mainwidget.cpp: mainwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwidget.h -o moc_mainwidget.cpp

moc_imagewidget.cpp: imagewidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) imagewidget.h -o moc_imagewidget.cpp

moc_cameraprocess.cpp: cameraprocess.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) cameraprocess.h -o moc_cameraprocess.cpp

moc_bluetoothprocess.cpp: bluetoothprocess.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) bluetoothprocess.h -o moc_bluetoothprocess.cpp

moc_textedit.cpp: mycanvas.h \
		textedit.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) textedit.h -o moc_textedit.cpp

moc_mycanvas.cpp: mycanvas.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mycanvas.h -o moc_mycanvas.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwidget.h \
		textedit.h \
		mycanvas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwidget.o: mainwidget.cpp mainwidget.h \
		imagewidget.h \
		cameraprocess.h \
		bluetoothprocess.h \
		textedit.h \
		mycanvas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwidget.o mainwidget.cpp

imagewidget.o: imagewidget.cpp imagewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagewidget.o imagewidget.cpp

capture.o: capture.cpp capture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o capture.o capture.cpp

formatconvert.o: formatconvert.cpp formatconvert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formatconvert.o formatconvert.cpp

cameraprocess.o: cameraprocess.cpp capture.h \
		cameraprocess.h \
		formatconvert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cameraprocess.o cameraprocess.cpp

bluetoothprocess.o: bluetoothprocess.cpp bluetoothprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bluetoothprocess.o bluetoothprocess.cpp

textedit.o: textedit.cpp textedit.h \
		mycanvas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textedit.o textedit.cpp

mycanvas.o: mycanvas.cpp mycanvas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mycanvas.o mycanvas.cpp

moc_mainwidget.o: moc_mainwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwidget.o moc_mainwidget.cpp

moc_imagewidget.o: moc_imagewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imagewidget.o moc_imagewidget.cpp

moc_cameraprocess.o: moc_cameraprocess.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cameraprocess.o moc_cameraprocess.cpp

moc_bluetoothprocess.o: moc_bluetoothprocess.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bluetoothprocess.o moc_bluetoothprocess.cpp

moc_textedit.o: moc_textedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_textedit.o moc_textedit.cpp

moc_mycanvas.o: moc_mycanvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mycanvas.o moc_mycanvas.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

